// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZF626BXBBUMen-zE9WUD1PbUC9HSyGM4',
    appId: '1:272006067912:web:a8638248f5be3a1a0697fd',
    messagingSenderId: '272006067912',
    projectId: 'time-tracker-app-28db8',
    authDomain: 'time-tracker-app-28db8.firebaseapp.com',
    storageBucket: 'time-tracker-app-28db8.appspot.com',
    measurementId: 'G-WXTFWP940J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqYbZ3uUOzc9RxgGjQsZkC8kiH0Jqv4O0',
    appId: '1:272006067912:android:72ce51cd558a47d10697fd',
    messagingSenderId: '272006067912',
    projectId: 'time-tracker-app-28db8',
    storageBucket: 'time-tracker-app-28db8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvjkEWA5LfsC2VjluHViWdupSeuKnR0k',
    appId: '1:272006067912:ios:24040a1dad173afe0697fd',
    messagingSenderId: '272006067912',
    projectId: 'time-tracker-app-28db8',
    storageBucket: 'time-tracker-app-28db8.appspot.com',
    androidClientId: '272006067912-b9c78c3kgorp6q0ps0otd7kfc56q0ii0.apps.googleusercontent.com',
    iosClientId: '272006067912-8jsh7vjvc2d8u2oie7h2jne64gf3e1ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.time',
  );
}
